### ISSUE TITLE
Use next/image

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/neosense-landing#3]
To improve page speed, use next/image

<img width="689" alt="Screenshot 2023-01-25 at 22 20 27" src="https://user-images.githubusercontent.com/311343/214693575-52e94d1c-93ad-4d00-822b-652a1235522f.png">

**Comment by haricnugraha** [comment]
Next.js default image optimization loader is not available for the exported applications. Unless we use other loader. More info https://nextjs.org/docs/messages/export-image-api

**Comment by nicnocquee** [comment]
Ah I see. Ok, let's close this issue for now.
