### ISSUE TITLE
Add quick import feature

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/neosense-landing#4]
In this section,

<img width="478" alt="Screenshot 2023-01-25 at 22 21 48" src="https://user-images.githubusercontent.com/311343/214693828-b0bb4b0e-2312-4b2c-83bd-4364b15d4e3d.png">

Add a feature item:

Title: Quickly probe multiple URLs
Description: Import URLs to probe quickly from sitemap, Postman, HAR, and more!

**Comment by haricnugraha** [comment]
Too many items on larger screen (768px width).

![main-feature](https://user-images.githubusercontent.com/15191978/214758631-f79258ad-2cbc-42b9-8475-e28695041071.png)

**Comment by nicnocquee** [comment]
hmm, any suggestions?

**Comment by haricnugraha** [comment]
I'll try to use the mobile layout for the 768px width screen.
