### ISSUE TITLE
Add another item in this section

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/neosense-landing#6]
<img width="955" alt="Screenshot 2023-01-25 at 22 27 04" src="https://user-images.githubusercontent.com/311343/214694907-1717a021-94e7-4e76-a20d-c6d0f51a957c.png">

Small text: Synthetic Monitoring
Title: Configure the requests from simple to the complex one
Description: Send the request you want to send every time Neosense probes your server including the headers and the body. You can even chain multiple requests one another.

Small text: Organize probes
Title: Create organizations and projects to organize your probes
Description: You can group multiple probes in the same project for convenience. You can also create multiple organizations to group multiple projects. Furthermore, you can invite other users to manage organizations, projects, and the probes.

**Comment by haricnugraha** [comment]
Added here [4835bd7](https://github.com/hyperjumptech/neosense-landing/commit/4835bd7a3a170cacca32d8ccbe1876655550e8c9).
